name: reviewdog

on:
    # Runs on pushes targeting the default branch
    push:
      branches: [ "main" ]
      paths-ignore:
        - '**.md'
    pull_request:
      branches: [ "main" ]
      paths-ignore:
        - '**.md'

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: "src/"